In [2]:
numbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

sum_odd = 0
sum_even = 0

for num in numbers:
    if num % 2 == 0:
        sum_even += num
    else:
        sum_odd += num

print(f"Sum of odd numbers: {sum_odd}")
print(f"Sum of even numbers: {sum_even}")

Sum of odd numbers: 25
Sum of even numbers: 30

In [3]:
numbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

smallest_number = min(numbers)

print(f"Smallest number: {smallest_number}")

Smallest number: 1

In [4]:
total_sum = sum(num for num in range(50, 101) if num % 3 == 0 and num % 5 != 0)

print(f"Sum of numbers between 50 and 100 that are divisible by 3 and not divisible by 5: {total_sum}")

Sum of numbers between 50 and 100 that are divisible by 3 and not divisible by 5: 1050

In [5]:
numbers = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100}

second_highest = sorted(numbers, reverse=True)[1]

print(f"Second highest number: {second_highest}")

Second highest number: 90

In [6]:
num = int(input("Enter a number: "))

factorial = 1
for i in range(1, num + 1):
	factorial *= i

print(f"Factorial of {num} is: {factorial}")

Enter a number: 5
Factorial of 5 is: 120

In [8]:
num = int(input("Enter the number: "))

fibonacci = [0, 1]
for i in range(2, num):
    fibonacci.append(fibonacci[-1] + fibonacci[-2])

print("Fibonacci series:", fibonacci[:num])

Enter the number: 5
Fibonacci series: [0, 1, 1, 2, 3]